language: php
php:
  - 7.4
before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-lowest
script:
  - vendor/bin/phpcs --report-full --standard=PSR2 src
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-text --verbose --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
